//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListAllBooking
    {
        public string Seat { get; set; }
        public int BookingId { get; set; }
        public int FlightId { get; set; }
        public int UserId { get; set; }
        public int Id { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public System.DateTime ArrivalTime { get; set; }
        public System.DateTime DepartureTime { get; set; }
        public decimal Price { get; set; }
    }
}
